site_name: Bluepad32
site_url: https://retro.moe/
site_author: Ricardo Quesada
site_description: >-
  A Bluetooth controller "host" for the ESP32, ESP32-S3, ESP32-C3, Raspberry Pi Pico W and Posix (Linux, macOS).
  Add Bluetooth gamepad, mouse and keyboard support to your projects easily.
  In other words, it allows you to control a robot using a DualSense controller.

repo_url: https://github.com/ricardoquesada/bluepad32
repo_name: ricardoquesada/bluepad32

copyright: Copyright &copy; 2019-2024 Ricardo Quesada & contributors

edit_uri: blob/develop/docs

watch:
  - README.md
  - CHANGELOG.md
  - AUTHORS.md
  - LICENSE
  - CONTRIBUTING.md

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Getting Help: getting_help.md
  - Controllers:
    - supported_gamepads.md
    - supported_mice.md
    - supported_keyboards.md
    - 'How to pair a DualShock3': pair_ds3.md
  - Platforms:
    - 'Arduino + ESP32 board': plat_arduino.md
    - 'Arduino + NINA-W10 board': plat_nina.md
    - 'CircuitPython + AirLift board': plat_airlift.md
    - 'ESP32 + ESP-IDF (raw API)': plat_esp32.md
    - 'Pico W + Pico SDK (raw API)': plat_picow.md
    - 'Unijoysticle board': plat_unijoysticle.md
    - 'MightyMiggy board': plat_mightymiggy.md
  - "Programmer's Guide":
    - 'Raw API': programmers_guide_raw.md
    - 'Arduino API': programmers_guide_arduino.md
    - 'CircuitPython API': programmers_guide_circuitpython.md
  - Developer Notes:
    - 'Flashing firmware': firmware_setup.md
    - adding_new_platform.md
    - 'Architecture': architecture.md
    - developer_notes.md
    - 'Issue Tracker': https://github.com/ricardoquesada/bluepad32/issues
  - About:
    - Authors: authors.md
    - license.md
    - 'Contributing': contributing.md
    - 'Release Notes': release_notes.md
    - FAQ.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    #- navigation.tabs
  font: false
  icon:
    repo: fontawesome/brands/github
  logo: images/logo_mkdocs_mini.png
  favicon: images/favicon.png

extra:
  analytics:
    provider: google
    property: G-FXKBEY2NKF

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - toc:
      permalink: true

plugins:
  - include-markdown
  - search

